[destination.snowflake.credentials]
database = "hr_project_db" # fill this in!
password = "hampus1234" # fill this in!
username = "hampus" # fill this in!
host = "jm72079.west-europe.azure" # fill this in!
warehouse = "hr_project_wh" # fill this in!
role = "ingest_role" # fill this in!